# Generated by Django 6.0.1 on 2026-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('offline', 'Очное посешение'), ('sbp', 'Перевод по системе СБП')], max_length=20, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('scheduled', 'Мероприятие назначено'), ('completed', 'Завершено')], default='new', max_length=20, verbose_name='Статус')),
                ('room_name', models.CharField(max_length=255, verbose_name='Название помещения')),
                ('conference_date', models.DateTimeField(verbose_name='Дата и время начала конференции')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ('-created_at',),
            },
        ),
    ]
